name = "musiclog-ai"
account_id = "049ff5e84ecf636b53b162cbb580aae6"
main = "src/worker.ts"
compatibility_date = "2024-05-29"

[vars]
DEEPSEEK_MODEL = "deepseek-chat"

[[kv_namespaces]]
binding = "KG"
id = "97fecbd575ad41ed8aae56e69ad19d86"



[[rules]]
type = "Text"
globs = ["**/*.html"]
